version: '2'

services:
  mysql:
    image: lucydb
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: root
      MYSQL_DATABASE: frontend_wp
    ports:
      - 3320:3306
    volumes:
      - .volumes/mysql/:/var/lib/mysql/
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql # db host
      PMA_USER: root
      PMA_PASSWORD: 123456
    ports:
      - 91:80
    depends_on:
      - mysql
  wpfrontend:
    image: wp
    volumes:
      - ./source/blog-frontend/:/var/www/html/
    ports:
      - 90:80
    depends_on:
      - mysql
